/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package controle;

import conexao.conexao;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author milaw
 */
public class frmFila extends javax.swing.JDialog {

    conexao con_brecho;
    
    public frmFila() {
        
        con_brecho = new conexao();
        con_brecho.conecta();
        
        setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();
        ImageIcon icon = new ImageIcon("src/img/loopo.png");
        setIconImage(icon.getImage());
        setTitle("Gerenciamento da Fila");
        
        con_brecho.executaSQL("select * from fila order by cod_fila");
        preencherTabela();
        posicionarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        entrar8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        tpesquisar = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tcodfila = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tidvest = new javax.swing.JTextField();
        anterior = new javax.swing.JButton();
        proximo = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        primeiro = new javax.swing.JButton();
        salvarFila = new javax.swing.JButton();
        alterarFila = new javax.swing.JButton();
        excluirFila = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        novo1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        entrar8.setBackground(new java.awt.Color(81, 4, 4));
        entrar8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrar8.setForeground(new java.awt.Color(255, 255, 255));
        entrar8.setText("Voltar");
        entrar8.setToolTipText("");
        entrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar8ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 4, 4));
        jLabel1.setText("Gerenciar Filas");

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Código Fila", "ID Vestuário"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        tpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpesquisarActionPerformed(evt);
            }
        });

        pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-2906 (1).png"))); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(81, 4, 4));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(81, 4, 4));
        jLabel2.setText("Código Fila:");

        tcodfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tcodfilaActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(81, 4, 4));
        jLabel3.setText("ID Vestuário");

        tidvest.setToolTipText("");
        tidvest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tidvestActionPerformed(evt);
            }
        });

        anterior.setBackground(new java.awt.Color(81, 4, 4));
        anterior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        anterior.setForeground(new java.awt.Color(255, 255, 255));
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        proximo.setBackground(new java.awt.Color(81, 4, 4));
        proximo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proximo.setForeground(new java.awt.Color(255, 255, 255));
        proximo.setText("Próximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        ultimo.setBackground(new java.awt.Color(81, 4, 4));
        ultimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ultimo.setForeground(new java.awt.Color(255, 255, 255));
        ultimo.setText("Último");
        ultimo.setToolTipText("");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        primeiro.setBackground(new java.awt.Color(81, 4, 4));
        primeiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        primeiro.setForeground(new java.awt.Color(255, 255, 255));
        primeiro.setText("Primeiro");
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(tcodfila, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tidvest, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(proximo)
                    .addComponent(primeiro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(anterior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tcodfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tidvest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anterior)
                            .addComponent(primeiro))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(proximo)
                            .addComponent(ultimo))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        salvarFila.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvarFila.setForeground(new java.awt.Color(255, 255, 255));
        salvarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-file-5327 (1).png"))); // NOI18N
        salvarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarFilaActionPerformed(evt);
            }
        });

        alterarFila.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarFila.setForeground(new java.awt.Color(255, 255, 255));
        alterarFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notes-and-pencil-black-outline-22356.png"))); // NOI18N
        alterarFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarFilaActionPerformed(evt);
            }
        });

        excluirFila.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluirFila.setForeground(new java.awt.Color(255, 255, 255));
        excluirFila.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-10402 (1).png"))); // NOI18N
        excluirFila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirFilaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Pesquisar pelo ID do Vestuário");

        novo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        novo1.setForeground(new java.awt.Color(255, 255, 255));
        novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-soma-32.png"))); // NOI18N
        novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(tpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addComponent(pesquisar))
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(novo1)
                            .addGap(18, 18, 18)
                            .addComponent(salvarFila)
                            .addGap(18, 18, 18)
                            .addComponent(alterarFila)
                            .addGap(18, 18, 18)
                            .addComponent(excluirFila)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(entrar8))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(228, 228, 228))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(novo1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(entrar8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(salvarFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(excluirFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(alterarFila, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void entrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar8ActionPerformed
       this.dispose();
    }//GEN-LAST:event_entrar8ActionPerformed

    private void tpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpesquisarActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
                                       try
                                        {
                                            String pesquisa = "select * from fila where cod_fila like '" + tpesquisar.getText() + "%'";
                                            con_brecho.executaSQL(pesquisa);
                                        
                                            if(con_brecho.resultset.first())
                                            {
                                                preencherTabela();
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null, "\n Não existe dados com este parâmetro!!", "Mensagm do Programa", JOptionPane.INFORMATION_MESSAGE);
                                            }
                                        }
                                        catch(SQLException errosql)
                                        {
                                            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!!: \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }  
    }//GEN-LAST:event_pesquisarActionPerformed

    private void tcodfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tcodfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tcodfilaActionPerformed

    private void tidvestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tidvestActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tidvestActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.previous();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior");
                                        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.next();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro.");
                                        }
    }//GEN-LAST:event_proximoActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.last();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro.");
                                        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void salvarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarFilaActionPerformed
                                        String idvestuario = tidvest.getText();
                                        
                                        try
                                        {
                                            String insert_sql = "insert into fila (id_vestuario) values ('" + idvestuario + "')";
                                            con_brecho.statement.executeUpdate(insert_sql);
                                            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                            
                                            con_brecho.executaSQL("select * from fila order by id_vestuario");
                                            preencherTabela();
                                        }
                                        catch(SQLException errosql)
                                        {
                                            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }
    }//GEN-LAST:event_salvarFilaActionPerformed

    private void alterarFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarFilaActionPerformed

                String idvestuario = tidvest.getText();

                String sql;
                
                String msg="";
                try {
                    if(tcodfila.getText().equals("")){
                        sql="insert into fila (id_vestuario) values ('"+ idvestuario +"')";
                        msg="Gravação de um novo registro";
                    } else {
                        sql = "update fila set id_vestuario='" + idvestuario + "' where cod_fila=" + tcodfila.getText();
                        msg="Alteração de registro";
                    }
                    con_brecho.statement.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso.","Mensagem do programa",JOptionPane.INFORMATION_MESSAGE);
 
                    con_brecho.executaSQL("select * from fila order by cod_fila");
                    preencherTabela(); 
                }
                catch(SQLException errosql) {
                    JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n "+errosql,"Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_alterarFilaActionPerformed

    private void excluirFilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirFilaActionPerformed
                                         String sql;

                                        try
                                        {
                                            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
                                            
                                            if(resposta == 0)
                                            {
                                                sql = "delete from fila where cod_fila = " + tcodfila.getText();
                                                
                                                int excluir = con_brecho.statement.executeUpdate(sql);
                                                if (excluir == 1)
                                                {
                                                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                                    con_brecho.executaSQL("select * from fila order by cod_fila");
                                                    con_brecho.resultset.first();
                                                    preencherTabela();
                                                    posicionarRegistro();
                                                }
                                                else 
                                                {
                                                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                                }
                                            }
                                        }
                                        catch(SQLException excecao)
                                        {
                                            JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }
    }//GEN-LAST:event_excluirFilaActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_primeiroActionPerformed

    private void novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo1ActionPerformed
    tidvest.setText("");
    tidvest.requestFocus();
    }//GEN-LAST:event_novo1ActionPerformed
 public void preencherTabela()
    {
       tabela.getColumnModel().getColumn(0).setPreferredWidth(8);
       tabela.getColumnModel().getColumn(1).setPreferredWidth(8);
       
       DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
       modelo.setNumRows(0);
       
       try
       {
           con_brecho.resultset.beforeFirst();
           while(con_brecho.resultset.next())
           {
               modelo.addRow(new Object[]
               {
                  con_brecho.resultset.getString("cod_fila"), con_brecho.resultset.getString("id_vestuario")
               });
           }
       }
       catch(SQLException erro)
       {
           JOptionPane.showMessageDialog(null, "\nErro ao listar dados da tabela!! :\n" + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
       }
    }

    public void mostrar_Dados()
    {
        try
        {
            tcodfila.setText(con_brecho.resultset.getString("cod_fila"));
            tidvest.setText(con_brecho.resultset.getString("id_vestuario"));

        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void posicionarRegistro()
    {
        try
        {
            con_brecho.resultset.first(); //posiciona o primeiro registro da tabela
            mostrar_Dados(); //chama o método que irá buscar o dado da tabela
        } 
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel posicionar no primeiro registro: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarFila;
    private javax.swing.JButton anterior;
    private javax.swing.JButton entrar8;
    private javax.swing.JButton excluirFila;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton novo1;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton primeiro;
    private javax.swing.JButton proximo;
    private javax.swing.JButton salvarFila;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tcodfila;
    private javax.swing.JTextField tidvest;
    private javax.swing.JTextField tpesquisar;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
