package controle;

import conexao.conexao;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public final class frmPedido extends javax.swing.JDialog {

    conexao con_brecho;
    
    public frmPedido() {
        
        con_brecho = new conexao();
        con_brecho.conecta();
        
        setModalityType(ModalityType.APPLICATION_MODAL);
        initComponents();
        ImageIcon icon = new ImageIcon("src/img/loopo.png");
        setIconImage(icon.getImage());
        setTitle("Gerenciamento do Pedido");
        
        con_brecho.executaSQL("select * from pedido order by id_cliente");
        preencherTabela();
        posicionarRegistro();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        id_cliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        codfila = new javax.swing.JTextField();
        anterior = new javax.swing.JButton();
        ultimo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        numfila = new javax.swing.JTextField();
        proximo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        primeiro = new javax.swing.JButton();
        dtpedido = new javax.swing.JFormattedTextField();
        salvarPedido = new javax.swing.JButton();
        alterarPedido = new javax.swing.JButton();
        excluirPedido = new javax.swing.JButton();
        entrar8 = new javax.swing.JButton();
        pesquisar = new javax.swing.JButton();
        tpesquisa = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        novo1 = new javax.swing.JButton();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(81, 4, 4));
        jLabel1.setText("Gerenciar Pedidos");

        tabela.setAutoCreateRowSorter(true);
        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Cliente", "Cod Fila", " Num Fila", "Data do Pedido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(81, 4, 4));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(81, 4, 4));
        jLabel2.setText("ID Cliente:");

        id_cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                id_clienteActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(81, 4, 4));
        jLabel3.setText("Cod Fila:");

        codfila.setToolTipText("");
        codfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codfilaActionPerformed(evt);
            }
        });

        anterior.setBackground(new java.awt.Color(81, 4, 4));
        anterior.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        anterior.setForeground(new java.awt.Color(255, 255, 255));
        anterior.setText("Anterior");
        anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorActionPerformed(evt);
            }
        });

        ultimo.setBackground(new java.awt.Color(81, 4, 4));
        ultimo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ultimo.setForeground(new java.awt.Color(255, 255, 255));
        ultimo.setText("Último");
        ultimo.setToolTipText("");
        ultimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(81, 4, 4));
        jLabel4.setText("Num Fila:");

        numfila.setToolTipText("");
        numfila.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numfilaActionPerformed(evt);
            }
        });

        proximo.setBackground(new java.awt.Color(81, 4, 4));
        proximo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        proximo.setForeground(new java.awt.Color(255, 255, 255));
        proximo.setText("Próximo");
        proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(81, 4, 4));
        jLabel5.setText("Data do Pedido:");

        primeiro.setBackground(new java.awt.Color(81, 4, 4));
        primeiro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        primeiro.setForeground(new java.awt.Color(255, 255, 255));
        primeiro.setText("Primeiro");
        primeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primeiroActionPerformed(evt);
            }
        });

        try {
            dtpedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##  ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabel4)
                                .addGap(54, 54, 54))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(codfila, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(numfila, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                            .addComponent(dtpedido)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(id_cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(primeiro)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(proximo)))
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(anterior)
                    .addComponent(ultimo, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addComponent(id_cliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(anterior)
                            .addComponent(primeiro))
                        .addGap(19, 19, 19)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ultimo)
                            .addComponent(proximo)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(codfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(numfila, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(dtpedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 22, Short.MAX_VALUE))
        );

        salvarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        salvarPedido.setForeground(new java.awt.Color(255, 255, 255));
        salvarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/save-file-5327 (1).png"))); // NOI18N
        salvarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvarPedidoActionPerformed(evt);
            }
        });

        alterarPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        alterarPedido.setForeground(new java.awt.Color(255, 255, 255));
        alterarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/notes-and-pencil-black-outline-22356.png"))); // NOI18N
        alterarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarPedidoActionPerformed(evt);
            }
        });

        excluirPedido.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        excluirPedido.setForeground(new java.awt.Color(255, 255, 255));
        excluirPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/delete-10402 (1).png"))); // NOI18N
        excluirPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirPedidoActionPerformed(evt);
            }
        });

        entrar8.setBackground(new java.awt.Color(81, 4, 4));
        entrar8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        entrar8.setForeground(new java.awt.Color(255, 255, 255));
        entrar8.setText("Voltar");
        entrar8.setToolTipText("");
        entrar8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entrar8ActionPerformed(evt);
            }
        });

        pesquisar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        pesquisar.setForeground(new java.awt.Color(255, 255, 255));
        pesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search-2906 (1).png"))); // NOI18N
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });

        tpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tpesquisaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 153, 153));
        jLabel8.setText("Pesquisar pelo Cod_Fila");

        novo1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        novo1.setForeground(new java.awt.Color(255, 255, 255));
        novo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/icons8-soma-32.png"))); // NOI18N
        novo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novo1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(novo1)
                        .addGap(25, 25, 25)
                        .addComponent(salvarPedido)
                        .addGap(24, 24, 24)
                        .addComponent(alterarPedido)
                        .addGap(26, 26, 26)
                        .addComponent(excluirPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(entrar8))
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(tpesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(pesquisar))
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(241, 241, 241))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(salvarPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(alterarPedido, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(novo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(entrar8)
                        .addComponent(excluirPedido)))
                .addGap(51, 51, 51))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void id_clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_id_clienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_id_clienteActionPerformed

    private void codfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codfilaActionPerformed

    private void anteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.previous();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o registro anterior.");
                                        }
    }//GEN-LAST:event_anteriorActionPerformed

    private void ultimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimoActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.last();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o último registro.");
                                        }
    }//GEN-LAST:event_ultimoActionPerformed

    private void numfilaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numfilaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numfilaActionPerformed

    private void proximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.next();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o próximo registro.");
                                        }
    }//GEN-LAST:event_proximoActionPerformed

    private void salvarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvarPedidoActionPerformed
                                        String idcliente = id_cliente.getText();
                                        String codigofila = codfila.getText();
                                        String numero_fila = numfila.getText();
                                        String dt_pedido = dtpedido.getText();
                                        
                                        try
                                        {
                                            String insert_sql = "insert into pedido (id_cliente, cod_fila, num_fila, data_pedido) values ('" + idcliente + "','" + codigofila + "', '" + numero_fila + "', '" + dt_pedido + "')";
                                            con_brecho.statement.executeUpdate(insert_sql);
                                            JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso!!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                            
                                            con_brecho.executaSQL("select * from pedido order by id_cliente");
                                            preencherTabela();
                                        }
                                        catch(SQLException errosql)
                                        {
                                            JOptionPane.showMessageDialog(null, "\n Erro na gravação: \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }
    }//GEN-LAST:event_salvarPedidoActionPerformed

    private void alterarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarPedidoActionPerformed
                String idcliente = id_cliente.getText();
                String codigofila = codfila.getText();
                String numero_fila = numfila.getText();
                String dt_pedido = dtpedido.getText();
                String sql;
                
                String msg="";
                try {
                    if(id_cliente.getText().equals("")){
                        sql="insert into pedido (nome,data_nasc,telefone,email,endereco,cpf) values ('"+ idcliente+"','"+ codigofila+"','"+ numero_fila +"','"+ dt_pedido+"')";
                        msg="Gravação de um novo registro";
                    } else {
                        sql = "update cliente set cod_fila='" + codigofila + "', email='" + numero_fila + "', data_pedido'" + dt_pedido + "' where id_cliente=" + id_cliente.getText();
                        msg="Alteração de registro";
                    }
                    con_brecho.statement.executeUpdate(sql);
                    JOptionPane.showMessageDialog(null, "Gravação realizada com sucesso.","Mensagem do programa",JOptionPane.INFORMATION_MESSAGE);
 
                    con_brecho.executaSQL("select * from pedido order by id_cliente");
                    preencherTabela(); 
                }
                catch(SQLException errosql) {
                    JOptionPane.showMessageDialog(null, "\n Erro na gravação :\n "+errosql,"Mensagem do programa", JOptionPane.INFORMATION_MESSAGE);
                }
    }//GEN-LAST:event_alterarPedidoActionPerformed

    private void excluirPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirPedidoActionPerformed
                                         String sql;

                                        try
                                        {
                                            int resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja excluir o registro: ", "Confirmar Exclusão", JOptionPane.YES_NO_OPTION, 3);
                                            
                                            if(resposta == 0)
                                            {
                                                sql = "delete from pedido where id_cliente = " + id_cliente.getText();
                                                
                                                int excluir = con_brecho.statement.executeUpdate(sql);
                                                if (excluir == 1)
                                                {
                                                    JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                                    con_brecho.executaSQL("select * from pedido order by id_cliente");
                                                    con_brecho.resultset.first();
                                                    preencherTabela();
                                                    posicionarRegistro();
                                                }
                                                else 
                                                {
                                                    JOptionPane.showMessageDialog(null, "Operação cancelada pelo usuário!!", "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                                }
                                            }
                                        }
                                        catch(SQLException excecao)
                                        {
                                            JOptionPane.showMessageDialog(null, "Erro na exclusão: " + excecao, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }
    }//GEN-LAST:event_excluirPedidoActionPerformed

    private void entrar8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entrar8ActionPerformed
        this.dispose();
    }//GEN-LAST:event_entrar8ActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed
                                      try
                                        {
                                            String pesquisa = "select * from pedido where num_fila like '" + tpesquisa.getText() + "%'";
                                            con_brecho.executaSQL(pesquisa);
                                        
                                            if(con_brecho.resultset.first())
                                            {
                                                preencherTabela();
                                            }
                                            else
                                            {
                                                JOptionPane.showMessageDialog(null, "\n Não existe dados com este parâmetro!!", "Mensagm do Programa", JOptionPane.INFORMATION_MESSAGE);
                                            }
                                        }
                                        catch(SQLException errosql)
                                        {
                                            JOptionPane.showMessageDialog(null, "\n Os dados digitados não foram localizados!!: \n" + errosql, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
                                        }  
    }//GEN-LAST:event_pesquisarActionPerformed

    private void tpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tpesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tpesquisaActionPerformed

    private void primeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primeiroActionPerformed
                                       try
                                        {
                                            con_brecho.resultset.first();
                                            mostrar_Dados();
                                        }
                                        catch(SQLException erro)
                                        {
                                            JOptionPane.showMessageDialog(null, "Não foi possível acessar o primeiro registro.");
                                        }
    }//GEN-LAST:event_primeiroActionPerformed

    private void novo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novo1ActionPerformed
    id_cliente.setText("");
    codfila.setText("");
    numfila.setText("");
    dtpedido.setText("");
    id_cliente.requestFocus();
    }//GEN-LAST:event_novo1ActionPerformed
 public void preencherTabela()
    {
       tabela.getColumnModel().getColumn(0).setPreferredWidth(8);
       tabela.getColumnModel().getColumn(1).setPreferredWidth(8);
       tabela.getColumnModel().getColumn(2).setPreferredWidth(10);
       tabela.getColumnModel().getColumn(3).setPreferredWidth(50);
       
       DefaultTableModel modelo = (DefaultTableModel) tabela.getModel();
       modelo.setNumRows(0);
       
       try
       {
           con_brecho.resultset.beforeFirst();
           while(con_brecho.resultset.next())
           {
               modelo.addRow(new Object[]
               {
                  con_brecho.resultset.getString("id_cliente"), con_brecho.resultset.getString("cod_fila"), con_brecho.resultset.getString("num_fila"), con_brecho.resultset.getString("data_pedido")
               });
           }
       }
       catch(SQLException erro)
       {
           JOptionPane.showMessageDialog(null, "\nErro ao listar dados da tabela!! :\n" + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
       }
    }

    public void mostrar_Dados()
    {
        try
        {
            id_cliente.setText(con_brecho.resultset.getString("id_cliente"));
            codfila.setText(con_brecho.resultset.getString("cod_fila"));
            numfila.setText(con_brecho.resultset.getString("num_fila"));
            dtpedido.setText(con_brecho.resultset.getString("data_pedido"));
        }
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não localizou dados: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    
    public void posicionarRegistro()
    {
        try
        {
            con_brecho.resultset.first(); //posiciona o primeiro registro da tabela
            mostrar_Dados(); //chama o método que irá buscar o dado da tabela
        } 
        catch(SQLException erro)
        {
            JOptionPane.showMessageDialog(null, "Não foi possivel posicionar no primeiro registro: " + erro, "Mensagem do Programa", JOptionPane.INFORMATION_MESSAGE);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterarPedido;
    private javax.swing.JButton anterior;
    private javax.swing.JTextField codfila;
    private javax.swing.JFormattedTextField dtpedido;
    private javax.swing.JButton entrar8;
    private javax.swing.JButton excluirPedido;
    private javax.swing.JTextField id_cliente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton novo1;
    private javax.swing.JTextField numfila;
    private javax.swing.JButton pesquisar;
    private javax.swing.JButton primeiro;
    private javax.swing.JButton proximo;
    private javax.swing.JButton salvarPedido;
    private javax.swing.JTable tabela;
    private javax.swing.JTextField tpesquisa;
    private javax.swing.JButton ultimo;
    // End of variables declaration//GEN-END:variables
}
